export const patientItem=[
    {
      "name": "Jane Doe",
      "email": "patient1@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user1.jpg",
      "address": "100 Main Street, City0",
      "gender": "female",
      "contactNumber": "+1234567890"
    },
    {
      "name": "John Smith",
      "email": "patient2@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user2.jpg",
      "address": "101 Elm Street, City1",
      "gender": "male",
      "contactNumber": "+1234567891"
    },
    {
      "name": "Alice Johnson",
      "email": "patient3@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user3.jpg",
      "address": "102 Oak Street, City2",
      "gender": "female",
      "contactNumber": "+1234567892"
    },
    {
      "name": "Bob Lee",
      "email": "patient4@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user4.jpg",
      "address": "103 Pine Avenue, City3",
      "gender": "male",
      "contactNumber": "+1234567893"
    },
    {
      "name": "Emma Davis",
      "email": "patient5@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user5.jpg",
      "address": "104 Maple Lane, City4",
      "gender": "female",
      "contactNumber": "+1234567894"
    },
    {
      "name": "Michael Brown",
      "email": "patient6@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user6.jpg",
      "address": "105 Cedar Road, City0",
      "gender": "male",
      "contactNumber": "+1234567895"
    },
    {
      "name": "Olivia Garcia",
      "email": "patient7@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user7.jpg",
      "address": "106 Birch Blvd, City1",
      "gender": "female",
      "contactNumber": "+1234567896"
    },
    {
      "name": "William Martinez",
      "email": "patient8@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user8.jpg",
      "address": "107 Spruce Way, City2",
      "gender": "male",
      "contactNumber": "+1234567897"
    },
    {
      "name": "Ava Rodriguez",
      "email": "patient9@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user9.jpg",
      "address": "108 Willow Drive, City3",
      "gender": "female",
      "contactNumber": "+1234567898"
    },
    {
      "name": "James Wilson",
      "email": "patient10@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user10.jpg",
      "address": "109 Chestnut Circle, City4",
      "gender": "male",
      "contactNumber": "+1234567899"
    },
    {
      "name": "Jane Doe",
      "email": "patient11@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user11.jpg",
      "address": "110 Main Street, City0",
      "gender": "female",
      "contactNumber": "+12345678100"
    },
    {
      "name": "John Smith",
      "email": "patient12@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user12.jpg",
      "address": "111 Elm Street, City1",
      "gender": "male",
      "contactNumber": "+12345678101"
    },
    {
      "name": "Alice Johnson",
      "email": "patient13@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user13.jpg",
      "address": "112 Oak Street, City2",
      "gender": "female",
      "contactNumber": "+12345678102"
    },
    {
      "name": "Bob Lee",
      "email": "patient14@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user14.jpg",
      "address": "113 Pine Avenue, City3",
      "gender": "male",
      "contactNumber": "+12345678103"
    },
    {
      "name": "Emma Davis",
      "email": "patient15@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user15.jpg",
      "address": "114 Maple Lane, City4",
      "gender": "female",
      "contactNumber": "+12345678104"
    },
    {
      "name": "Michael Brown",
      "email": "patient16@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user16.jpg",
      "address": "115 Cedar Road, City0",
      "gender": "male",
      "contactNumber": "+12345678105"
    },
    {
      "name": "Olivia Garcia",
      "email": "patient17@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user17.jpg",
      "address": "116 Birch Blvd, City1",
      "gender": "female",
      "contactNumber": "+12345678106"
    },
    {
      "name": "William Martinez",
      "email": "patient18@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user18.jpg",
      "address": "117 Spruce Way, City2",
      "gender": "male",
      "contactNumber": "+12345678107"
    },
    {
      "name": "Ava Rodriguez",
      "email": "patient19@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user19.jpg",
      "address": "118 Willow Drive, City3",
      "gender": "female",
      "contactNumber": "+12345678108"
    },
    {
      "name": "James Wilson",
      "email": "patient20@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user20.jpg",
      "address": "119 Chestnut Circle, City4",
      "gender": "male",
      "contactNumber": "+12345678109"
    },
    {
      "name": "Jane Doe",
      "email": "patient21@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user21.jpg",
      "address": "120 Main Street, City0",
      "gender": "female",
      "contactNumber": "+12345678110"
    },
    {
      "name": "John Smith",
      "email": "patient22@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user22.jpg",
      "address": "121 Elm Street, City1",
      "gender": "male",
      "contactNumber": "+12345678111"
    },
    {
      "name": "Alice Johnson",
      "email": "patient23@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user23.jpg",
      "address": "122 Oak Street, City2",
      "gender": "female",
      "contactNumber": "+12345678112"
    },
    {
      "name": "Bob Lee",
      "email": "patient24@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user24.jpg",
      "address": "123 Pine Avenue, City3",
      "gender": "male",
      "contactNumber": "+12345678113"
    },
    {
      "name": "Emma Davis",
      "email": "patient25@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user25.jpg",
      "address": "124 Maple Lane, City4",
      "gender": "female",
      "contactNumber": "+12345678114"
    },
    {
      "name": "Michael Brown",
      "email": "patient26@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user26.jpg",
      "address": "125 Cedar Road, City0",
      "gender": "male",
      "contactNumber": "+12345678115"
    },
    {
      "name": "Olivia Garcia",
      "email": "patient27@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user27.jpg",
      "address": "126 Birch Blvd, City1",
      "gender": "female",
      "contactNumber": "+12345678116"
    },
    {
      "name": "William Martinez",
      "email": "patient28@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user28.jpg",
      "address": "127 Spruce Way, City2",
      "gender": "male",
      "contactNumber": "+12345678117"
    },
    {
      "name": "Ava Rodriguez",
      "email": "patient29@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user29.jpg",
      "address": "128 Willow Drive, City3",
      "gender": "female",
      "contactNumber": "+12345678118"
    },
    {
      "name": "James Wilson",
      "email": "patient30@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user30.jpg",
      "address": "129 Chestnut Circle, City4",
      "gender": "male",
      "contactNumber": "+12345678119"
    },
    {
      "name": "Jane Doe",
      "email": "patient31@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user31.jpg",
      "address": "130 Main Street, City0",
      "gender": "female",
      "contactNumber": "+12345678120"
    },
    {
      "name": "John Smith",
      "email": "patient32@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user32.jpg",
      "address": "131 Elm Street, City1",
      "gender": "male",
      "contactNumber": "+12345678121"
    },
    {
      "name": "Alice Johnson",
      "email": "patient33@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user33.jpg",
      "address": "132 Oak Street, City2",
      "gender": "female",
      "contactNumber": "+12345678122"
    },
    {
      "name": "Bob Lee",
      "email": "patient34@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user34.jpg",
      "address": "133 Pine Avenue, City3",
      "gender": "male",
      "contactNumber": "+12345678123"
    },
    {
      "name": "Emma Davis",
      "email": "patient35@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user35.jpg",
      "address": "134 Maple Lane, City4",
      "gender": "female",
      "contactNumber": "+12345678124"
    },
    {
      "name": "Michael Brown",
      "email": "patient36@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user36.jpg",
      "address": "135 Cedar Road, City0",
      "gender": "male",
      "contactNumber": "+12345678125"
    },
    {
      "name": "Olivia Garcia",
      "email": "patient37@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user37.jpg",
      "address": "136 Birch Blvd, City1",
      "gender": "female",
      "contactNumber": "+12345678126"
    },
    {
      "name": "William Martinez",
      "email": "patient38@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user38.jpg",
      "address": "137 Spruce Way, City2",
      "gender": "male",
      "contactNumber": "+12345678127"
    },
    {
      "name": "Ava Rodriguez",
      "email": "patient39@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user39.jpg",
      "address": "138 Willow Drive, City3",
      "gender": "female",
      "contactNumber": "+12345678128"
    },
    {
      "name": "James Wilson",
      "email": "patient40@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user40.jpg",
      "address": "139 Chestnut Circle, City4",
      "gender": "male",
      "contactNumber": "+12345678129"
    },
    {
      "name": "Jane Doe",
      "email": "patient41@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user41.jpg",
      "address": "140 Main Street, City0",
      "gender": "female",
      "contactNumber": "+12345678130"
    },
    {
      "name": "John Smith",
      "email": "patient42@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user42.jpg",
      "address": "141 Elm Street, City1",
      "gender": "male",
      "contactNumber": "+12345678131"
    },
    {
      "name": "Alice Johnson",
      "email": "patient43@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user43.jpg",
      "address": "142 Oak Street, City2",
      "gender": "female",
      "contactNumber": "+12345678132"
    },
    {
      "name": "Bob Lee",
      "email": "patient44@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user44.jpg",
      "address": "143 Pine Avenue, City3",
      "gender": "male",
      "contactNumber": "+12345678133"
    },
    {
      "name": "Emma Davis",
      "email": "patient45@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user45.jpg",
      "address": "144 Maple Lane, City4",
      "gender": "female",
      "contactNumber": "+12345678134"
    },
    {
      "name": "Michael Brown",
      "email": "patient46@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user46.jpg",
      "address": "145 Cedar Road, City0",
      "gender": "male",
      "contactNumber": "+12345678135"
    },
    {
      "name": "Olivia Garcia",
      "email": "patient47@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user47.jpg",
      "address": "146 Birch Blvd, City1",
      "gender": "female",
      "contactNumber": "+12345678136"
    },
    {
      "name": "William Martinez",
      "email": "patient48@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user48.jpg",
      "address": "147 Spruce Way, City2",
      "gender": "male",
      "contactNumber": "+12345678137"
    },
    {
      "name": "Ava Rodriguez",
      "email": "patient49@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user49.jpg",
      "address": "148 Willow Drive, City3",
      "gender": "female",
      "contactNumber": "+12345678138"
    },
    {
      "name": "James Wilson",
      "email": "patient50@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/user50.jpg",
      "address": "149 Chestnut Circle, City4",
      "gender": "male",
      "contactNumber": "+12345678139"
    }
  ]

  export const doctorItem=[
    {
      "name": "Dr. John Doe",
      "email": "doctor1@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/john.jpg",
      "contactNumber": "+1234567890",
      "address": "123 Medical Lane, Health City",
      "registrationNumber": "MED123456",
      "experience": 10,
      "gender": "male",
      "appointmentFee": 100,
      "qualification": "MBBS, MD",
      "currentWorkingPlace": "City Hospital",
      "designation": "Cardiologist"
    },
    {
      "name": "Dr. Jane Smith",
      "email": "doctor2@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/jane.jpg",
      "contactNumber": "+1987654321",
      "address": "456 Wellness Ave, Health City",
      "registrationNumber": "MED654321",
      "experience": 8,
      "gender": "female",
      "appointmentFee": 120,
      "qualification": "MBBS, PhD",
      "currentWorkingPlace": "Wellness Clinic",
      "designation": "Neurologist"
    },
    {
      "name": "Dr. Mark Allen",
      "email": "doctor3@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/mark.jpg",
      "contactNumber": "+1122334455",
      "address": "789 Health St, Wellness Town",
      "registrationNumber": "MED112233",
      "experience": 5,
      "gender": "male",
      "appointmentFee": 80,
      "qualification": "MBBS",
      "currentWorkingPlace": "Bright Hospital",
      "designation": "General Practitioner"
    },
    {
      "name": "Dr. Emily Green",
      "email": "doctor4@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/emily.jpg",
      "contactNumber": "+1222333444",
      "address": "123 Heartbeat Road, Health City",
      "registrationNumber": "MED223344",
      "experience": 15,
      "gender": "female",
      "appointmentFee": 150,
      "qualification": "MBBS, MS",
      "currentWorkingPlace": "CardioCare Clinic",
      "designation": "Cardiac Surgeon"
    },
    {
      "name": "Dr. Sarah Lee",
      "email": "doctor5@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/sarah.jpg",
      "contactNumber": "+1333444555",
      "address": "321 Hope St, Green Valley",
      "registrationNumber": "MED556677",
      "experience": 20,
      "gender": "female",
      "appointmentFee": 200,
      "qualification": "MD, FACS",
      "currentWorkingPlace": "Green Valley Medical Center",
      "designation": "Plastic Surgeon"
    },
    {
      "name": "Dr. David King",
      "email": "doctor6@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/david.jpg",
      "contactNumber": "+1444556677",
      "address": "987 Healthy Lane, Health Park",
      "registrationNumber": "MED778899",
      "experience": 12,
      "gender": "male",
      "appointmentFee": 95,
      "qualification": "MBBS, DNB",
      "currentWorkingPlace": "Health Park Hospital",
      "designation": "Orthopedic Surgeon"
    },
    {
      "name": "Dr. Olivia Brown",
      "email": "doctor7@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/olivia.jpg",
      "contactNumber": "+1555667788",
      "address": "543 Recovery Road, Health City",
      "registrationNumber": "MED998877",
      "experience": 7,
      "gender": "female",
      "appointmentFee": 110,
      "qualification": "MBBS, MD",
      "currentWorkingPlace": "Recovery Clinic",
      "designation": "Gynecologist"
    },
    {
      "name": "Dr. Kevin White",
      "email": "doctor8@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/kevin.jpg",
      "contactNumber": "+1666778899",
      "address": "456 Vital Ave, Wellness City",
      "registrationNumber": "MED665544",
      "experience": 3,
      "gender": "male",
      "appointmentFee": 70,
      "qualification": "MBBS",
      "currentWorkingPlace": "Wellness Care Center",
      "designation": "Family Physician"
    },
    {
      "name": "Dr. Mia Carter",
      "email": "doctor9@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/mia.jpg",
      "contactNumber": "+1777889900",
      "address": "234 Health Ave, City Center",
      "registrationNumber": "MED446677",
      "experience": 6,
      "gender": "female",
      "appointmentFee": 130,
      "qualification": "MD, MPH",
      "currentWorkingPlace": "Public Health Clinic",
      "designation": "Public Health Specialist"
    },
    {
      "name": "Dr. Lucas Wright",
      "email": "doctor10@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/lucas.jpg",
      "contactNumber": "+1888990011",
      "address": "678 Treatment St, Medical Town",
      "registrationNumber": "MED554433",
      "experience": 9,
      "gender": "male",
      "appointmentFee": 90,
      "qualification": "MBBS, DGO",
      "currentWorkingPlace": "Women’s Health Clinic",
      "designation": "Obstetrician"
    },
    {
      "name": "Dr. Emma Harris",
      "email": "doctor11@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/emma.jpg",
      "contactNumber": "+1999001122",
      "address": "321 Healthy Way, Wellness District",
      "registrationNumber": "MED223355",
      "experience": 11,
      "gender": "female",
      "appointmentFee": 140,
      "qualification": "MBBS, MCh",
      "currentWorkingPlace": "Spine Care Center",
      "designation": "Neurosurgeon"
    },
    {
      "name": "Dr. Nathan Cooper",
      "email": "doctor12@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/nathan.jpg",
      "contactNumber": "+1222334455",
      "address": "789 Wellness Ave, Green Hills",
      "registrationNumber": "MED887766",
      "experience": 14,
      "gender": "male",
      "appointmentFee": 115,
      "qualification": "MBBS, MD",
      "currentWorkingPlace": "Heart & Vascular Center",
      "designation": "Cardiologist"
    },
    {
      "name": "Dr. Isabella Davis",
      "email": "doctor13@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/isabella.jpg",
      "contactNumber": "+1444332211",
      "address": "654 Treatment Blvd, Heart Town",
      "registrationNumber": "MED445577",
      "experience": 4,
      "gender": "female",
      "appointmentFee": 125,
      "qualification": "MD",
      "currentWorkingPlace": "Heart Clinic",
      "designation": "Echocardiogram Specialist"
    },
    {
      "name": "Dr. George Hall",
      "email": "doctor14@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/george.jpg",
      "contactNumber": "+1555443322",
      "address": "234 Recovery Lane, Health City",
      "registrationNumber": "MED221144",
      "experience": 18,
      "gender": "male",
      "appointmentFee": 160,
      "qualification": "MBBS, FRCS",
      "currentWorkingPlace": "Surgical Center",
      "designation": "Surgeon"
    },
    {
      "name": "Dr. Chloe Moore",
      "email": "doctor15@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/chloe.jpg",
      "contactNumber": "+1666888999",
      "address": "987 Medical Park, Health Zone",
      "registrationNumber": "MED334455",
      "experience": 13,
      "gender": "female",
      "appointmentFee": 100,
      "qualification": "MD, PhD",
      "currentWorkingPlace": "Cancer Treatment Center",
      "designation": "Oncologist"
    },
    {
      "name": "Dr. James Lewis",
      "email": "doctor16@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/james.jpg",
      "contactNumber": "+1777990011",
      "address": "456 Pathway Lane, Health City",
      "registrationNumber": "MED556633",
      "experience": 10,
      "gender": "male",
      "appointmentFee": 130,
      "qualification": "MBBS, MS",
      "currentWorkingPlace": "Bone Care Center",
      "designation": "Orthopedic Specialist"
    },
    {
      "name": "Dr. Ava Miller",
      "email": "doctor17@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/ava.jpg",
      "contactNumber": "+1888001122",
      "address": "345 Wellness St, City Park",
      "registrationNumber": "MED778811",
      "experience": 6,
      "gender": "female",
      "appointmentFee": 90,
      "qualification": "MBBS, MS",
      "currentWorkingPlace": "Eye Clinic",
      "designation": "Ophthalmologist"
    },
    {
      "name": "Dr. Benjamin Carter",
      "email": "doctor18@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/benjamin.jpg",
      "contactNumber": "+1999002233",
      "address": "876 Health Ave, Medical Town",
      "registrationNumber": "MED998811",
      "experience": 17,
      "gender": "male",
      "appointmentFee": 180,
      "qualification": "MD, FRCS",
      "currentWorkingPlace": "Advanced Surgery Center",
      "designation": "Cardiothoracic Surgeon"
    },
    {
      "name": "Dr. Sophia Taylor",
      "email": "doctor19@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/sophia.jpg",
      "contactNumber": "+1222446688",
      "address": "234 Health Plaza, Greenfield",
      "registrationNumber": "MED556677",
      "experience": 5,
      "gender": "female",
      "appointmentFee": 110,
      "qualification": "MBBS, MD",
      "currentWorkingPlace": "Fertility Clinic",
      "designation": "Reproductive Endocrinologist"
    },
    {
      "name": "Dr. Matthew Scott",
      "email": "doctor20@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/matthew.jpg",
      "contactNumber": "+1333224455",
      "address": "789 Healthy Blvd, Medical Valley",
      "registrationNumber": "MED667788",
      "experience": 14,
      "gender": "male",
      "appointmentFee": 125,
      "qualification": "MBBS, DNB",
      "currentWorkingPlace": "Family Health Clinic",
      "designation": "Pediatrician"
    },
    {
      "name": "Dr. Lily Evans",
      "email": "doctor21@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/lily.jpg",
      "contactNumber": "+1444667788",
      "address": "456 Heart St, Medical Zone",
      "registrationNumber": "MED112233",
      "experience": 3,
      "gender": "female",
      "appointmentFee": 95,
      "qualification": "MD",
      "currentWorkingPlace": "Children's Clinic",
      "designation": "Pediatric Cardiologist"
    },
    {
      "name": "Dr. Oliver Walker",
      "email": "doctor22@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/oliver.jpg",
      "contactNumber": "+1555778899",
      "address": "987 Wellness Blvd, City Center",
      "registrationNumber": "MED332211",
      "experience": 8,
      "gender": "male",
      "appointmentFee": 140,
      "qualification": "MD, FACS",
      "currentWorkingPlace": "Advanced Care Hospital",
      "designation": "NeuroSurgeon"
    },
    {
      "name": "Dr. Charlotte Green",
      "email": "doctor23@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/charlotte.jpg",
      "contactNumber": "+1666779988",
      "address": "321 Treatment Road, City Plaza",
      "registrationNumber": "MED223344",
      "experience": 16,
      "gender": "female",
      "appointmentFee": 150,
      "qualification": "MD, PhD",
      "currentWorkingPlace": "Dermatology Clinic",
      "designation": "Dermatologist"
    },
    {
      "name": "Dr. Zachary Adams",
      "email": "doctor24@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/zachary.jpg",
      "contactNumber": "+1777889900",
      "address": "123 Vital St, Health Zone",
      "registrationNumber": "MED445577",
      "experience": 9,
      "gender": "male",
      "appointmentFee": 105,
      "qualification": "MD, MSc",
      "currentWorkingPlace": "Mental Health Clinic",
      "designation": "Psychiatrist"
    },
    {
      "name": "Dr. Grace White",
      "email": "doctor25@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/grace.jpg",
      "contactNumber": "+1888996677",
      "address": "543 Pathway Lane, City Park",
      "registrationNumber": "MED667788",
      "experience": 10,
      "gender": "female",
      "appointmentFee": 100,
      "qualification": "MBBS, MD",
      "currentWorkingPlace": "Cancer Care Center",
      "designation": "Radiologist"
    },
    {
      "name": "Dr. Jack Robinson",
      "email": "doctor26@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/jack.jpg",
      "contactNumber": "+1999001122",
      "address": "678 Heart Blvd, Health City",
      "registrationNumber": "MED889900",
      "experience": 11,
      "gender": "male",
      "appointmentFee": 120,
      "qualification": "MD, DNB",
      "currentWorkingPlace": "Emergency Care Center",
      "designation": "Emergency Physician"
    },
    {
      "name": "Dr. Leah King",
      "email": "doctor27@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/leah.jpg",
      "contactNumber": "+1222334444",
      "address": "456 Recovery Ave, Wellness Park",
      "registrationNumber": "MED990011",
      "experience": 4,
      "gender": "female",
      "appointmentFee": 125,
      "qualification": "MBBS",
      "currentWorkingPlace": "Rehabilitation Center",
      "designation": "Rehabilitation Specialist"
    },
    {
      "name": "Dr. Samuel Foster",
      "email": "doctor28@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/samuel.jpg",
      "contactNumber": "+1333445566",
      "address": "123 Healing St, City Central",
      "registrationNumber": "MED445533",
      "experience": 2,
      "gender": "male",
      "appointmentFee": 85,
      "qualification": "MBBS",
      "currentWorkingPlace": "Healing Clinic",
      "designation": "General Surgeon"
    },
    {
      "name": "Dr. Penelope Allen",
      "email": "doctor29@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/penelope.jpg",
      "contactNumber": "+1444556677",
      "address": "321 Medical Blvd, Health Plaza",
      "registrationNumber": "MED998877",
      "experience": 6,
      "gender": "female",
      "appointmentFee": 100,
      "qualification": "MBBS",
      "currentWorkingPlace": "Health Center",
      "designation": "General Practitioner"
    },
    {
      "name": "Dr. Anthony Collins",
      "email": "doctor30@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/anthony.jpg",
      "contactNumber": "+1555667788",
      "address": "678 Health St, Wellness City",
      "registrationNumber": "MED223344",
      "experience": 9,
      "gender": "male",
      "appointmentFee": 140,
      "qualification": "MD, DNB",
      "currentWorkingPlace": "Dental Care Center",
      "designation": "Dentist"
    }
]

export const adminItem=[
    {
      "name": "John Smith",
      "email": "admin2@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/john2.jpg",
      "address": "456 Elm Street, Shelbyville",
      "gender": "male",
      "contactNumber": "+1234567802"
    },
    {
      "name": "Alice Johnson",
      "email": "admin3@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/alice3.jpg",
      "address": "789 Oak Street, Capital City",
      "gender": "female",
      "contactNumber": "+1234567803"
    },
    {
      "name": "Robert Brown",
      "email": "admin4@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/robert4.jpg",
      "address": "321 Pine Street, Ogdenville",
      "gender": "male",
      "contactNumber": "+1234567804"
    },
    {
      "name": "Emily Davis",
      "email": "admin5@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/emily5.jpg",
      "address": "654 Maple Avenue, North Haverbrook",
      "gender": "female",
      "contactNumber": "+1234567805"
    },
    {
      "name": "Michael Wilson",
      "email": "admin6@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/michael6.jpg",
      "address": "159 Cedar Drive, Brockway",
      "gender": "male",
      "contactNumber": "+1234567806"
    },
    {
      "name": "Laura Martinez",
      "email": "admin7@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/laura7.jpg",
      "address": "753 Birch Road, Springfield",
      "gender": "female",
      "contactNumber": "+1234567807"
    },
    {
      "name": "David Anderson",
      "email": "admin8@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/david8.jpg",
      "address": "852 Willow Way, Shelbyville",
      "gender": "male",
      "contactNumber": "+1234567808"
    },
    {
      "name": "Sophia Thomas",
      "email": "admin9@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/sophia9.jpg",
      "address": "951 Poplar Lane, Capital City",
      "gender": "female",
      "contactNumber": "+1234567809"
    },
    {
      "name": "James Lee",
      "email": "admin10@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/james10.jpg",
      "address": "357 Palm Blvd, Ogdenville",
      "gender": "male",
      "contactNumber": "+1234567810"
    },
    {
      "name": "Olivia Walker",
      "email": "admin11@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/olivia11.jpg",
      "address": "246 Cypress Ave, North Haverbrook",
      "gender": "female",
      "contactNumber": "+1234567811"
    },
    {
      "name": "Daniel Hall",
      "email": "admin12@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/daniel12.jpg",
      "address": "135 Fir Street, Brockway",
      "gender": "male",
      "contactNumber": "+1234567812"
    },
    {
      "name": "Grace Allen",
      "email": "admin13@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/grace13.jpg",
      "address": "864 Redwood Dr, Springfield",
      "gender": "female",
      "contactNumber": "+1234567813"
    },
    {
      "name": "Henry Young",
      "email": "admin14@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/henry14.jpg",
      "address": "123 Ash Court, Shelbyville",
      "gender": "male",
      "contactNumber": "+1234567814"
    },
    {
      "name": "Ella Hernandez",
      "email": "admin15@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/ella15.jpg",
      "address": "321 Larch Lane, Capital City",
      "gender": "female",
      "contactNumber": "+1234567815"
    },
    {
      "name": "Chloe Wright",
      "email": "admin17@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/chloe17.jpg",
      "address": "789 Spruce St, North Haverbrook",
      "gender": "female",
      "contactNumber": "+1234567817"
    },
    {
      "name": "Matthew Lopez",
      "email": "admin18@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/matthew18.jpg",
      "address": "951 Dogwood Pl, Brockway",
      "gender": "male",
      "contactNumber": "+1234567818"
    },
    {
      "name": "Ava Scott",
      "email": "admin19@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/ava19.jpg",
      "address": "753 Juniper Cir, Springfield",
      "gender": "female",
      "contactNumber": "+1234567819"
    },
    {
      "name": "Benjamin Green",
      "email": "admin20@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/benjamin20.jpg",
      "address": "852 Hickory Blvd, Shelbyville",
      "gender": "male",
      "contactNumber": "+1234567820"
    },
    {
      "name": "Lily Adams",
      "email": "admin21@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/lily21.jpg",
      "address": "357 Beech Ct, Capital City",
      "gender": "female",
      "contactNumber": "+1234567821"
    },
    {
      "name": "Andrew Nelson",
      "email": "admin22@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/andrew22.jpg",
      "address": "246 Chestnut Rd, Ogdenville",
      "gender": "male",
      "contactNumber": "+1234567822"
    },
    {
      "name": "Sofia Carter",
      "email": "admin23@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/sofia23.jpg",
      "address": "135 Alder St, North Haverbrook",
      "gender": "female",
      "contactNumber": "+1234567823"
    },
    {
      "name": "Jack Mitchell",
      "email": "admin24@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/jack24.jpg",
      "address": "864 Hemlock Ln, Brockway",
      "gender": "male",
      "contactNumber": "+1234567824"
    },
    {
      "name": "Natalie Perez",
      "email": "admin25@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/natalie25.jpg",
      "address": "123 Walnut St, Springfield",
      "gender": "female",
      "contactNumber": "+1234567825"
    },
    {
      "name": "Luke Roberts",
      "email": "admin26@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/luke26.jpg",
      "address": "321 Magnolia Dr, Shelbyville",
      "gender": "male",
      "contactNumber": "+1234567826"
    },
    {
      "name": "Zoe Turner",
      "email": "admin27@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/zoe27.jpg",
      "address": "456 Aspen Ave, Capital City",
      "gender": "female",
      "contactNumber": "+1234567827"
    },
    {
      "name": "Nathan Phillips",
      "email": "admin28@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/nathan28.jpg",
      "address": "789 Sycamore Blvd, Ogdenville",
      "gender": "male",
      "contactNumber": "+1234567828"
    },
    {
      "name": "Hannah Campbell",
      "email": "admin29@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/hannah29.jpg",
      "address": "951 Cottonwood Ln, North Haverbrook",
      "gender": "female",
      "contactNumber": "+1234567829"
    },
    {
      "name": "Logan Murphy",
      "email": "admin30@gmail.com",
      "password": "12345678",
      "photo": "https://example.com/images/logan30.jpg",
      "address": "753 Ironwood Pl, Brockway",
      "gender": "male",
      "contactNumber": "+1234567830"
    }
  ]
  